#PROCEDURE FOR SHOWING STUDENTS TABLE
CREATE OR REPLACE PROCEDURE shstudent(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM students;
END;
/

#PROCEDURE OR SHOWING TAS TABLE
CREATE OR REPLACE PROCEDURE shtas(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM tas;
END;
/

#PROCEDURE FOR SHOWING COURSES TABLE
CREATE OR REPLACE PROCEDURE shcourses(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM courses;
END;
/

#PROCEDURE FOR SHOWING CLASSES TABLES
CREATE OR REPLACE PROCEDURE shclasses(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM classes;
END;
/

#PROCEDURE FOR SHOWING ENROLLMENTS TABLES
CREATE OR REPLACE PROCEDURE shenroll(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM enrollments;
END;
/

#PROCEDURE FOR SHOWING PREREQUISITES TABLES
CREATE OR REPLACE PROCEDURE shprerequi(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM prerequisites;
END;
/

#PROCEDURES FOR SHOWING LOGS TABLE
CREATE OR REPLACE PROCEDURE shlogs(ab OUT SYS_REFCURSOR )
AS
BEGIN 
OPEN ab FOR SELECT * FROM logs;
END;
/
